quiz_lib=[
    ['about','exactly'],
    ['above','below'],
    ['absence','presence'],
    ['abundance','lack'],
    ['to accept','to refuse'],
    ['accidental','intentional'],
    ['active','lazy'],
    ['to add','to subtract'],
    ['to admit','to deny'],
    ['adult','child'],
    ['advanced','elementary'],
    ['affirmative','negative'],
    ['afraid','brave'],
    ['after','before'],
    ['against','for'],
    ['alike','different'],
    ['alive','dead'],
    ['all','none'],
    ['to allow','to forbid'],
    ['already','not yet'],
    ['always','never'],
    ['ancient','modern'],
    ['ancestor','descendant'],
    ['to agree','to refuse,to argue'],
    ['amateur','professional'],
    ['to amuse','to bore'],
    ['ancestor','descendant'],
    ['angel','devil'],
    ['animal','human'],
    ['to annoy','to satisfy'],
    ['to answer','to ask'],
    ['answer','question'],
    ['antonym','synonym'],
    ['apart','together'],
    ['approximately','exactly'],
    ['to argue','to agree'],
    ['to arrest','to free,to set free'],
    ['arrival','departure'],
    ['to arrive','to depart,to leave'],
    ['artificial','natural'],
    ['to ask','to answer'],
    ['asleep','awake'],
    ['to attack','to defend'],
    ['attack','defence,protection'],
    ['attic','cellar'],
    ['autumn','spring'],
    ['awake','asleep'],
    ['awful','delicious,nice,pleasant'],
    ['back','in front of'],
    ['background','foreground'],
    ['backward','forward'],
    ['bad','good'],
    ['bad luck','fortune,good luck'],
    ['beauty','ugliness'],
    ['before','after'],
    ['to begin','to end,to stop,to finish'],
    ['beginning','end,ending'],
    ['behind','in front of'],
    ['below','above'],
    ['best','worst'],
    ['better','worse'],
    ['beautiful','ugly'],
    ['big','small,little'],
    ['birth','death'],
    ['bitter','sweet'],
    ['black','white'],
    ['blunt','sharp'],
    ['body','soul'],
    ['to bore','to amuse,to be interested in'],
    ['boring','exciting,interesting'],
    ['to borrow','to lend'],
    ['bottom','top'],
    ['boy','girl'],
    ['brave','cowardly,afraid'],
    ['to break','to mend,to fix'],
    ['broad','narrow'],
    ['brother','sister'],
    ['to build','to destroy'],
    ['busy','lazy'],
    ['to buy','to sell'],
    ['calm','excited'],
    ['careful','careless'],
    ['careless','careful'],
    ['to catch','to miss,to throw'],
    ['ceiling','floor'],
    ['cellar','attic'],
    ['centre','outskirts,suburb'],
    ['certainly','probably'],
    ['changeable','constant'],
    ['cheap','expensive'],
    ['child','adult,grown-up'],
    ['children','parents'],
    ['clean','dirty'],
    ['clear','cloudy'],
    ['clever','stupid'],
    ['to close','to open'],
    ['closed','open'],
    ['cloudy','clear,sunny,bright'],
    ['cold','hot'],
    ['to come','to go'],
    ['comedy','drama,tragedy'],
    ['complicated','simple'],
    ['compliment','insult'],
    ['compulsory','voluntary'],
    ['to connect','to separate'],
    ['consonant','vowel'],
    ['constant','changeable'],
    ['construction','destruction'],
    ['to continue','to interrupt'],
    ['cool','warm'],
    ['correct','false,wrong'],
    ['courage','fear'],
    ['courageous','cowardly'],
    ['cowardly','brave,courageous'],
    ['to create','to destroy'],
    ['cruel','human,kind,humane'],
    ['to cry (schreien)','to whisper'],
    ['to cry (weinen)','to laugh'],
    ['to damage','to repair'],
    ['danger','security,safety'],
    ['dangerous','safe'],
    ['dark','light'],
    ['daughter','son'],
    ['dawn','dusk'],
    ['day','night'],
    ['dead','alive'],
    ['death','birth,life'],
    ['deep','shallow'],
    ['defeat','victory'],
    ['defence','attack'],
    ['to defend','to attack'],
    ['delicious','awful'],
    ['to deny','to admit'],
    ['to depart','to arrive'],
    ['departure','arrival'],
    ['desperate','hopeful'],
    ['to destroy','to build,to create,to form'],
    ['destruction','construction'],
    ['devil','angel'],
    ['dictatorship','republic'],
    ['to die','to live'],
    ['different','alike,equal,the same'],
    ['difficult','easy'],
    ['dirty','clean'],
    ['disease','health'],
    ['distant','near'],
    ['to divide','to unite'],
    ['division','unity'],
    ['to divorce','to marry'],
    ['divorce','marriage,wedding'],
    ['divorced','married'],
    ['domestic','foreign'],
    ['down','up'],
    ['downstairs','upstairs'],
    ['drama','comedy'],
    ['dry','humid,wet'],
    ['dull','interesting'],
    ['dusk','dawn'],
    ['early','late'],
    ['east','west'],
    ['easy','difficult,hard'],
    ['elementary','advanced'],
    ['to emigrate','to immigrate'],
    ['emigration','immigration'],
    ['empty','full'],
    ['to end','to begin'],
    ['end','beginning'],
    ['ending','beginning'],
    ['enemy','friend'],
    ['to enjoy','to hate'],
    ['to enter','to leave'],
    ['entrance','exit'],
    ['equal','different'],
    ['even (Zahlen)','odd'],
    ['evening','morning'],
    ['everybody','nobody'],
    ['everything','nothing'],
    ['exactly','about,approximately'],
    ['excited','calm'],
    ['exciting','boring'],
    ['to exclude','to include'],
    ['exit','entrance'],
    ['expensive','cheap'],
    ['export','import'],
    ['exposure','shelter'],
    ['extreme','moderate'],
    ['to fail','to succeed,to pass'],
    ['failure','success'],
    ['FALSE','correct,true'],
    ['far','near'],
    ['fast','slow'],
    ['fat','slim,thin'],
    ['fear','courage'],
    ['female','male'],
    ['few','many'],
    ['final','first'],
    ['to find','to lose'],
    ['to finish','to begin'],
    ['finish','start'],
    ['first','final,last'],
    ['to fix','to break'],
    ['flat','hilly'],
    ['floor','ceiling'],
    ['to follow','to lead'],
    ['to forbid','to allow,to let,to permit'],
    ['for','against'],
    ['foreground','background'],
    ['foreign','domestic'],
    ['foreigner','native'],
    ['to forget','to remember'],
    ['to form','to destroy'],
    ['fortune','bad luck'],
    ['forward','backward'],
    ['to free','to arrest'],
    ['to freeze','to melt'],
    ['frequently','occasionally'],
    ['fresh','old,stale'],
    ['friend','enemy'],
    ['front','rear'],
    ['in front of','back,behind'],
    ['full','empty'],
    ['funny','serious'],
    ['future','past,present']]